language: node_js
node_js:
- stable
- 6
- 4
deploy:
  provider: npm
  email: nathan@nfriedly.com
  api_key:
    secure: ZbWST7Hr9W0QRgHyBhP4gZhwuV1SguJeQvw2K6fUmlV6NJPzNqnrhTs27byF8WoXmaEubkT3FOCgg/ocauS83hyGMuU2TAMn4nR8pegmslFnxoiWaTPIPn/jGR9EswVxBK4nYuCMpgeJXkx62nrx9MtwmeHUdVeP3WkEC0uhfIo=
  on:
    tags: true
    repo: nfriedly/express-rate-limit
